"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getBatchedNodes = exports.assignMapValue = exports.assignValue = exports.getMap = exports.createMap = exports.getNode = exports.createNode = void 0;
require("module-alias/register");
var createNode_1 = require("@lib/api/declarations/createNode");
Object.defineProperty(exports, "createNode", { enumerable: true, get: function () { return createNode_1.createNode; } });
var getNode_1 = require("@lib/api/declarations/getNode");
Object.defineProperty(exports, "getNode", { enumerable: true, get: function () { return getNode_1.getNode; } });
var createMap_1 = require("@lib/api/declarations/createMap");
Object.defineProperty(exports, "createMap", { enumerable: true, get: function () { return createMap_1.createMap; } });
var getMap_1 = require("@lib/api/declarations/getMap");
Object.defineProperty(exports, "getMap", { enumerable: true, get: function () { return getMap_1.getMap; } });
var assignValue_1 = require("@lib/api/assignments/assignValue");
Object.defineProperty(exports, "assignValue", { enumerable: true, get: function () { return assignValue_1.assignValue; } });
var assignMapValue_1 = require("@lib/api/assignments/assignMapValue");
Object.defineProperty(exports, "assignMapValue", { enumerable: true, get: function () { return assignMapValue_1.assignMapValue; } });
var getBatchedNodes_1 = require("@lib/api/declarations/getBatchedNodes");
Object.defineProperty(exports, "getBatchedNodes", { enumerable: true, get: function () { return getBatchedNodes_1.getBatchedNodes; } });
